config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations:'users/registrations',sessions:'users/sessions'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'

  # resources :items, only: [:index, :show, :new, :edit]

  # root "items#new"
  resources :items ,only: [:index,:new,:create,:show,:edit] do
    collection do
      get 'get_children'
      get 'get_grand_children'
    end
  end
  resources :categories ,only: :new

  resources :card,only: [:new,:create,:destroy]

  resources :items,except: :index do
    resources :payments,only: [:new,:create]
  end

  get '/users/out', to: 'users#out'
  resources :users, only: [:show]

end

app/models/item.rb
class Item < ApplicationRecord
  validates :user_id,:images,:name,:description,:category,:condition_id,:shipment_fee_id,:shipment_region_id,:shipment_schedule_id,:price, presence: true
  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  # validates :condition, numericality:{other_than: 0, message: "「選択してください」以外を選択してください"}
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :user, class_name: "User"

    belongs_to_active_hash :condition
    validates :condition_id, numericality:{other_than: 0, message: "「選択してください」以外を選択してください"}
    belongs_to_active_hash :shipment_fee
    validates :shipment_fee_id, numericality:{other_than: 0, message: "「選択してください」以外を選択してください"}
    belongs_to_active_hash :shipment_region
    validates :shipment_region_id, numericality:{other_than: 0, message: "「選択してください」以外を選択してください"}
    belongs_to_active_hash :shipment_schedule
    validates :shipment_schedule_id, numericality:{other_than: 0, message: "「選択してください」以外を選択してください"}
  validates :price, presence: true, numericality:{greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, message: "300〜9,999,999円以内で入力してください"}

  belongs_to :category
  has_many    :images
  accepts_nested_attributes_for :images, allow_destroy: true
  # belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  belongs_to :buyer, class_name: "User",  optional: true

  # カテゴリーの単体テスト
  # 以下のコメントアウトは今後必要になるかもしれないので残しております
  # validate :category_is_grandchild

  # private

  # def category_is_grandchild
  #   if self.category.children.length != 0
  #     errors.add(:category, "not grandchild")
  #   end
  # end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.includes(:images).order('created_at DESC').limit(5)
    @parents = Category.where(ancestry: nil)
  end

  def new
    @item = Item.new
    @images = @item.images.build
    @parent_category = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    if @item.valid? && @item.save!
      redirect_to root_path controller: :items, action: :index
    else
      @parent_category = Category.where(ancestry: nil)
      @item.images.new
      render "new"
    end
  end

  def show
    @parents = Category.where(ancestry: nil)
  end

  def edit
    @item.user_id = current_user.id && user_signed_in?
    @parent_category = Category.where(ancestry: nil)
    @item.images.build
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render "edit"
    end
  end


  def get_children
    @categories = Category.where(ancestry: params[:category_id])
    respond_to do |format|
      format.json
    end
  end

  def get_grand_children
    @children_categories = Category.where(ancestry: params[:category_id])
    respond_to do |format|
      format.json
    end
  end


  def destroy
    if @item.user_id == current_user.id && @item.destroy
      redirect_to root_path
    end
  end



  private

  def item_params
    params.require(:item).permit(:images, :name, :description, :category, :brand, :condition_id, :shipment_fee_id, :shipment_region_id, :shipment_schedule_id, :price, :category_id, images_attributes: [:src, :id, :_destroy]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.bodyNew
  .containerNew
    .headerNew
      = link_to root_path do
        = image_tag "logo.png", class: "headerNew__logo"
    .formNew
      %section.formNew__block
      = form_with model:@item, local:true do |f|
        - if @item.errors.any?
          .formNew__alert
            %h2= "#{@item.errors.full_messages.count}件のエラーが発生しました。"
            %ul
              - @item.errors.full_messages.each do |message|
                %li= message
        .formNew__image
          .formNew__image--content
            .content
              .content__image
                %h3.content__image__title
                  出品画像
                  %span.require 必須
                %p.image_title 最大5枚までアップロードできます
                .content__image__select
                  .post__drop__box__container
                    .prev-content
                    .label-content
                      %label.image__select
                      %label{for: "item_images_attributes_0_src", class: "label-box", id: "label-box--0", style: "background-color: #eeeeee; width: 100%; height: 150px; margin: 0 auto; padding: 45px 0px; border: dotted 1px;"}
                        %pre.label-box__select__text{style: "text-align: center; font-size: 3px;"} クリックしてファイルをアップロード
                    .hidden-content
                      = f.fields_for  :images, {class: "image__select__input", type: "file"} do |i|
                        = i.file_field :src, class: "hidden-field"
                        %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][src]", id: "item_images_attributes_1_src"}
                        %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][src]", id: "item_images_attributes_2_src"}
                        %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][src]", id: "item_images_attributes_3_src"}
                        %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][src]", id: "item_images_attributes_4_src"}
                %p.image_note
        .formNew__description
          .formNew__description--content
            .content
              .content__description_name
                .content__description_name--title
                  %label 商品名
                  %span 必須
                = f.text_field :name, {class: "content__description_name--input", placeholder: "40字まで", type: "text"}
                %p.description_name_note
              .content__description_text
                .content__description_text--title
                  %label 商品の説明
                  %span 必須
                = f.text_area :description, {class: "content__description_text--textarea", placeholder: "商品の説明", rows: 1000}
                %p.character_count 0/1000
                %p.description_text_note
        .formNew__detail
          .formNew__detail--content
            .content
              .content__detail_category
                %p.detail_category 商品の詳細
                .content__detail_category--title
                  %label カテゴリー
                  %span 必須
                .content__detail_category--form
                  = f.collection_select :category_id, @parent_category,:id,:name,{prompt:"選択してください"}, {id:"item_category",class:"content__detail_category--select"}
                  %p.detail_category_note
              .content__detail_brand
                .content__detail_brand--title
                  %label ブランド
                  %span 任意
                = f.text_field :brand, {class: "content__detail_brand--input", placeholder: "例）ユニクロ", type: "text"}
              .content__detail_condition
                .content__detail_condition--title
                  %label 商品の状態
                  %span 必須
                -# = f.select :condition, [["選択してください", 0],["新品", 1],["未使用に近い", 2],["目立った傷や汚れなし", 3],["やや傷や汚れあり", 4]], {},class: "content__detail_condition--select"
                = f.collection_select :condition_id, Condition.all, :id, :name, {}, class: "content__detail_condition--select"
                %p.detail_condition_note
        .formNew__shipment
          .formNew__shipment--content
            .content
              .content__shipment_fee
                %p.shipment_fee 配送について
                .content__shipment_fee--title
                  %label 配送料の負担
                  %span 必須
                = f.collection_select :shipment_fee_id, ShipmentFee.all, :id, :name, {},class: "content__shipment_fee--select"
                %p.shipment_fee_note
              .content__shipment_region
                .content__shipment_region--title
                  %label 発送元の地域
                  %span 必須
                = f.collection_select :shipment_region_id, ShipmentRegion.all, :id, :name, {},class: "content__shipment_region--select"
                %p.shipment_region_note
              .content__shipment_schedule
                .content__shipment_schedule--title
                  %label 発送までの日数
                  %span 必須
                = f.collection_select :shipment_schedule_id, ShipmentSchedule.all, :id, :name, {},class: "content__shipment_schedule--select"
                %p.shipment_shedule_note
        .formNew__price
          .formNew__price--content
            .content
              .content__price
                %p.content__price--range 価格（¥300〜9,999,999）
                .content__price--title
                  %label 販売価格
                  %span.must 必須
                  %span.enn ￥
                  = f.number_field :price, {class: "price", placeholder: 0}
                %p.content__price--note
                .content__price--tax
                  %p 販売手数料（10%）
                  %span#tax ---
                .content__price--profit
                  %p 販売利益
                  %span#profit ---
        .formNew__send
          .formNew__send--content
            .content
              .content__send
                -if controller.action_name == "new"
                  = f.submit "出品する", {class: "content__send--button"}
                  = link_to "戻る", "#", class: "content__send--back"
                - else controller.action_name == "edit"
                  = f.submit "出品する", {class: "content__send--button"}
                  = link_to "戻る", "#", class: "content__send--back"

          .formNew__send--note
            %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
      .footerNew
        = link_to root_path do
          = image_tag "logo.png", class: "footerNew__logo"
          %p © FURIMA, Inc

app/views/items/index.html.haml
= render "common/main_header"


.main
  %section.main-Visual
    .content
      %h2.content__sub-title
        %br/
        人生を変えるフリマアプリ
      %p.content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .content__btn
        = link_to "#",class: 'apple-Btn' do
          = image_tag "app-store-icon.svg"
        = link_to "#",class: 'google-Btn' do
          = image_tag "google-play-icon.svg"
    .picture
  %section.top-Introduction
    %h2.sub-title
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          = image_tag "pict-reason-1.jpg"
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          = image_tag "pict-reason-2.jpg"
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number 3
          = image_tag "pict-reason-3.jpg"
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&amp;購入！
  %section.top-MiddleDl
    .top-MiddleDl__inner
      %h2.sub-title 会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to "#",class: 'apple-Btn' do
          = image_tag "app-store-icon.svg"
        = link_to "#",class: 'google-Btn' do
          = image_tag "google-play-icon.svg"
  %section.top-KeyFeatures
    %h2.head
      FURIMAの特徴
      .after
    .items
      %section.item
        %figure.item__img
          = image_tag "items-icon-01.svg"
        %h3.item__sub-title 簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          = image_tag "items-icon-02.svg"
        %h3.item__sub-title 売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.item
        %figure.item__img
          = image_tag "items-icon-03.svg"
        %h3.item__sub-title 様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupContainer__first
    .head ピックアップカテゴリー
    .productBox
      .productHead
        = link_to "#" do
          .title 新規投稿商品
      .productLists
        - @items.each do |item|
          = link_to item_path(item.id) do
            .productList
              - if item.buyer_id.present? 
                .productList__sold
                  .productList__sold--inner
                    SOLD
              - else
                .productList__not-sold
            .productList__img
              = image_tag item.images[0].src.url, class: "productList__img--url"
            .productList__body
              .name
                = item.name
              .details
                .details__price
                  .details__price--inner
                    = item.price
                    %span 円
                  %li
                    %i.fa.fa-star.likeIcon
                    1
                .details__tax 
                  (税込)
  %aside.Banner
    .inner
      %h2.inner__title
        だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text 今すぐ無料ダウンロード！
      .inner__icon
        = link_to "#",class: 'apple-Btn' do
          = image_tag "app-store-icon.svg"
        = link_to "#",class: 'google-Btn' do
          = image_tag "google-play-icon.svg"
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul
        %li.company
          =link_to "#" do
            %span 会社概要（運営会社）
        %li.policy
          =link_to "#" do
            %span プライバシーポリシー
        %li.regulation
          =link_to "#" do
            %span FURIMA利用規約
        %li.point
          =link_to "#" do
            %span ポイントに関する特約
    %li.content
      %h2.content__head FURIMAを見る
      %ul
        %li
          =link_to "#" do
            %span カテゴリー一覧
        %li
          =link_to "#" do
            %span ブランド一覧
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul
        %li
          %span FURIMAガイド
        %li
          =link_to "#" do
            %span FURIMAロゴ利用ガイドライン
        %li
          =link_to "#" do
            %span お知らせ
  .footer__logo
    =link_to "/" do
      = image_tag "FURIMA-logo-white.svg", class: "footer__logo--img"
  .copyright
    © FURIMA
=link_to "/items/new" do
  .purchase-Btn
    %span.purchase-Btn__text 出品する
    .purchase-Btn__icon
    = image_tag "camera.svg"

app/views/items/new.html.haml
= render partial: 'form'
= render 'layouts/error_messages', model: @item

app/views/items/show.html.haml
= render "common/main_header"

%nav.breadcrumbs
  %ul{style: "padding: 17px 0 16px; width: 100%; max-width: 1040px; font-size: 14px; margin: 0 auto; list-style: none;"}
    %li{style: "padding: 0 10px 0 0; float: left;"}
      = link_to href: "/", style:"text-decoration: none; color: #333;" do
        FURIMA
    %li{style: "padding: 0 10px 0 0; float: left;"}
      %i.fa.fa-angle-right{style: "display: inline-block; font: normal normal normal 14px/1 FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"}
    %li{style: "padding: 0 10px 0 0; float: left;"}
      = link_to href: "#", style:"text-decoration: none; color: #333;" do
        ベビー・キッズ
    %li{style: "padding: 0 10px 0 0; float: left;"}
      %i.fa.fa-angle-right{style: "display: inline-block; font: normal normal normal 14px/1 FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"}
    %li{style: "padding: 0 10px 0 0; float: left;"}
      = link_to href: "#", style:"text-decoration: none; color: #333;" do
        ベビー服(男女兼用)  ~95cm
    %li{style: "padding: 0 10px 0 0; float: left;"}
      %i.fa.fa-angle-right{style: "display: inline-block; font: normal normal normal 14px/1 FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"}
    %li{style: "padding: 0 10px 0 0; float: left;"}
      = link_to href: "#", style: "text-decoration: none; color: #333;" do
        アウター
    %li{style: "padding: 0 10px 0 0; float: left;"}
      %i.fa.fa-angle-right{style: "display: inline-block; font: normal normal normal 14px/1 FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased;"}
    %li{style: "font-weight: bold; padding: 0 10px 0 0; float: left;"}
      %div product3
.main
  .showmain
    .contentleftqq
    .contentright
      .topcontent
        .itembox
          %div.itembox__name
            = @item.name
          .itembox__body
            %div
              %div
                = image_tag @item.images[0].src.url, style: "height: 346px; width: 100%; object-fit: cover;"
                %div{style: "display: flex; justify-content: center; margin-top: 10px;"}
                  - @item.images.each do |image|
                    %div
                      = image_tag image.src.url, style: "height: 87px; width: 140px; object-fit: cover; margin-right: 5px;"
          .itembox__price
            .itembox__price-price
              = @item.price
              %span 円
            .itembox__price-detail
              %span
                (税込)
              %span
                送料込み
          .itemdetail
            = @item.description
          .table
            %table{border: "1"}
              %tbody
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} 出品者
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    = @item.user.nickname
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} カテゴリー
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    - @parents.each do |parent|
                      -if @item.category_id == parent.id
                        = link_to '#' do
                          = parent.name
                          %br                
                      - parent.children.each do |child|
                        -if @item.category_id == child.id
                          = link_to '#' do
                            = parent.name
                            %br
                          = link_to '#' do
                            = child.name
                            %br               
                        - child.children.each do |grandchild|
                          -if @item.category_id == grandchild.id
                            = link_to '#' do
                              = parent.name
                            %br
                            = link_to '#' do
                              = child.name
                            %br
                            = link_to '#' do
                              = grandchild.name
                            %br
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} ブランド
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    = @item.brand
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"}  商品の状態
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    = @item.condition.name
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} 配送料の負担
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    = @item.shipment_fee.name
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} 発送元の地域
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    %link_to{href: "#",style:"color: #3ccace;"}
                      = @item.shipment_region.name
                %tr
                  %th{style:"width: 152px; background-color: #eee; font-weight: 400; padding: 8px; border: 1px solid #dedede; font-size: 14px; text-align: center;"} 発送日の目安
                  %td{style:"width: 467px; padding: 15px 15px; border: 1px solid #dedede; font-size: 14px;"}
                    = @item.shipment_schedule.name
          .optionalarea
            %div{style: "margin: 10px 0 0;display: flex;"}
              %div#likeBtn.optionalbtn.likebtn{style: "margin-right: auto;padding: 6px 10px;border-radius: 40px;color: #3ccace;border: 1px solid #ffb340;"}
                %i.fa.fa-star{style: "display: inline-block;font: normal normal normal 14px/1 FontAwesome;font-size: inherit;text-rendering: auto;-webkit-font-smoothing: antialiased;color: #3ccace;"}
                お気に入り 0
            %div.optional
            %li.optionalbtn{style: "margin-top: 5px;"}
              = link_to href: "#",style: "padding: 6px 10px; margin-top: 10px; display: inline-block; border-radius: 4px; color: #333; border: 1px solid #333; text-decoration: none; font-size: normal;" do
                %i.fa.fa-flag{style: "display: inline-block;font: normal normal normal 14px/1 FontAwesome; text-rendering: auto; -webkit-font-smoothing: antialiased;"}
                  不適切な商品の通報
        - if user_signed_in? && current_user.id == @item.user_id
          .edit_deletebox{style: "background-color: #fff; margin: 24px 0px; padding: 20px 10px; height: 160px;"}
            %p.editbox
              = link_to '編集の編集', edit_item_path(@item.id), method: :get, class: "editbox__link", style: "display: inline-block; color: #ffffff; font-size: 14px; height: 50px; width: 100%; line-height: 50px; text-align: center; background-color: #ea352d; border-radius: 10px;"
            .deletebox
              = link_to 'この商品を削除する', item_path(@item.id), method: :delete, class: "deletebox__link", style: "display: inline-block; color: #ffffff; font-size: 14px; margin-top:20px; height: 50px; width: 100%; line-height: 50px; text-align: center; background-color: #aaaaaa; border-radius: 10px;"
        - elsif user_signed_in? && current_user.id != @item.user_id && !@item.buyer_id
          = link_to '購入画面に進む', new_item_payment_path(@item.id), method: :get, class: "paymentbox__link", style: "display: inline-block; color: #ffffff; font-size: 14px; margin-top:20px; height: 50px; width: 100%; line-height: 50px; text-align: center; background-color: #ea352d; border-radius: 10px;"
        .commentbox
          %div.commentcontents
          %form#new_comment.new_comment{"accept-charset" => "UTF-8", action: "#", method: "post"}
            %input{name: "utf8", type: "hidden", value: "✓"}/
            %input{name: "authenticity_token", type: "hidden", value: "/bKlXFzmZnYWuZdstnJ62bomGGRwX6OVc98x97W8mM3TK823CvzZol/dkwQe+jBZzFT0yaldaDumUkevxjczrg=="}/
            %textarea#comment_body{name: "comment[body]", required: "required",style: "width: 95%; min-height: 100px; padding: 10px;"}
              :preserve
            %p.noticemsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br/
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br/
            %button.commentbtn{name: "button", type: "submit"}
              %i.fa-comment
              コメントする
      %div.links
        %div.links__a
          = link_to href: "#",style: "text-decoration: none;" do
            %i.fa.fa-angle-left
            %span{style:"color: #3CCACE;"} 前の商品
        %div.links__b
          = link_to href: "#",style: "text-decoration: none;" do
            %span{style:"color: #3CCACE;"} 後ろの商品
            %i.fa.fa-angle-right
      .relateditems
        %a{href: "#",style: "display: block; margin: 70px 0 40px; color: #3CCACE; text-decoration: none; font-weight: bold; font-size: 22px; position: relative;"} ベビー・キッズをもっと見る
        .productlists
          .productlist
            = link_to href: "/products/8",style: "text-decoration: none;" do
              %figure.productlist--img{style: "width: 220px; height: 150px; position: relative; overflow: hidden; margin: 0; z-index: auto;"}
                %img{src: "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG",style: "width: 220px; height: 150px; object-fit: cover;"}/
              .productlist--body
                %div.name ee
                .details
                  %div{style: "display: flex; align-items: center; justify-content: space-between; list-style: none;font-size: 14px;"}
                    %li{style: "font-size: 15px;"}1000円
                    %li{style: "font-size: 15px;"}
                      %i.fa.fa-star.likeIcon
                      0
                  %div{style: "font-size: 10px;"} (税込)
  %aside.Banner
    .inner
      %h2.inner__title{style: "color: #fff;"}
        だれでもかんたん、人生を変えるフリマアプリ
      %p.inner__text{style: "color: #fff;"} 今すぐ無料ダウンロード！
      .inner__icon
        = link_to "#",class: 'apple-Btn',style: "margin-right: 5px;" do
          = image_tag "app-store-icon.svg"
        = link_to "#",class: 'google-Btn',style: "margin-left: 5px;" do
          = image_tag "google-play-icon.svg"
.footer
  %ul.contents
    %li.content
      %h2.content__head{style: "color: #fff;"} FURIMAについて
      %ul{style: "list-style: none;"}
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            会社概要（運営会社）
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            プライバシーポリシー
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            FURIMA利用規約
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            ポイントに関する特約
    %li.content
      %h2.content__head{style: "color: #fff;"} FURIMAを見る
      %ul{style: "list-style: none;"}
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            カテゴリー一覧
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            ブランド一覧
    %li.content
      %h2.content__head{style: "color: #fff;"} ヘルプ＆ガイド
      %ul{style: "list-style: none;"}
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          %a{href: "#"} FURIMAガイド
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li{style: "color: #fff; text-decoration: none; font-size: 12px; line-height: 32px;"}
          =link_to "#" do
            お知らせ
  .footer__logo
    =link_to "/" do
      = image_tag "FURIMA-logo-white.svg", style: "width: 100%; vertical-align: bottom;"
  %p{style: "font-size: 14px;margin: 0;padding: 0;color: #fff;"} © FURIMA
=link_to "#" do
  .purchase-Btn
    %span.purchase-Btn__text 出品する
    .purchase-Btn__icon
    = image_tag "camera.svg"