config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations:'users/registrations',sessions:'users/sessions'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'

  # resources :items, only: [:index, :show, :new, :edit]

  # root "items#new"
  resources :items ,only: [:index,:new,:create,:show,:edit] do
    collection do
      get 'get_children'
      get 'get_grand_children'
    end
  end
  resources :categories ,only: :new

  resources :card,only: [:new,:create,:destroy]

  resources :items,except: :index do
    resources :payments,only: [:new,:create]
  end

  get '/users/out', to: 'users#out'
  resources :users, only: [:show]

end

app/models/card.rb
class Card < ApplicationRecord
  validates :user, uniqueness: true
  validates :customer_id,:card_id, presence: true

  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :authenticate_user!
  def new
    @parents = Category.where(ancestry: nil)
    if current_user&.card
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(current_user.card.customer_id)
      @card = customer.cards.retrieve(current_user.card.card_id)
    else
      gon.api_key = ENV["PAYJP_PUBLIC_KEY"]
    end
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params["payjp-token"].blank?
      render :new
    else
      customer = Payjp::Customer.create(
        card: params["payjp-token"]
      )
      @card = Card.new(
        user_id: current_user.id,
        customer_id: customer.id,
        card_id: customer.default_card
      )
      if @card.save
        redirect_to new_card_path
      else
        gon.api_key = ENV["PAYJP_PUBLIC_KEY"]
        render :new
      end
    end
  end

  def destroy
    if Card.find(params[:id]).destroy
      redirect_to new_card_path
    end
  end

end

app/views/card/new.html.haml
= render "common/main_header"

.contents
  = render "common/left_side_menu"
  .contents__rightt
    - if current_user&.card
      .contents__rightt__head
        %h3 クレジットカード情報
      .contents__rightt__body
        .card--brand= @card.brand
        %label カード番号
        .card--num= "**** **** **** #{@card.last4}"
        - if @card.name
          %label カード氏名
          .card--name= @card.name
        =link_to "削除","/card/#{current_user.card.id}", method:"delete",class:"contents__rightt__body-btn"
    - else
      .contents__rightt__head
        %h3 クレジットカード情報入力
      = form_with url: card_index_path,local:true,id:"card__form",class:"contents__rightt__body" do |f|
        %input#card__form--inputHidden{type:"hidden",name:"payjp-token"}

        %label カード番号
        %span.contents__rightt__body-require 必須
        #card__form--number-form.payjs-outer

        %label 有効期限
        %span.contents__rightt__body-require 必須
        #card__form--expiry-form.payjs-outer

        %label セキリュティーコード
        %span.contents__rightt__body-require 必須
        #card__form--cvc-form.payjs-outer

        #card__form--errMessage
        = f.submit "登録する",id:"card__form--submit",class:"contents__rightt__body-btn"





%script{src: "https://js.pay.jp/v2/pay.js", type: "text/javascript"}

:javascript
  if(typeof gon != 'undefined'){

    const style = {
      base: {
        backgroundColor:'#ffffff',
        '::placeholder': {
          color: '#bbbbbb',
        }
      },
      invalid: {
        color: 'red',
      }
    }
    const stylenum = {
      base: {
        backgroundColor:'#ffffff',
        '::placeholder': {
          color: '#ffffff',
        }
      },
      invalid: {
        color: 'red',
      }
    }

    let payjp = Payjp(gon.api_key);
    let elements = payjp.elements();
    let numberElement = elements.create('cardNumber', {style: stylenum});
    let expiryElement = elements.create('cardExpiry', {style: style});
    let cvcElement = elements.create('cardCvc', {style: style});

    numberElement.mount('#card__form--number-form');
    expiryElement.mount('#card__form--expiry-form');
    cvcElement.mount('#card__form--cvc-form');

    $(".contents").on("click","#card__form--submit",
      function(e){
        e.preventDefault();
        payjp.createToken(expiryElement).then(function(response){
          if(response.error){
            $('#card__form--errMessage').text(response.error.message);
          }else{
            $("#card__form--inputHidden").attr("value",response.id);
            $("#card__form").submit();
          }
        });
      }
    );
  }