config/routes.rb
Rails.application.routes.draw do

  devise_for :users,controllers:{registrations:'users/registrations',sessions:'users/sessions'}
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#index'

  # resources :items, only: [:index, :show, :new, :edit]

  # root "items#new"
  resources :items ,only: [:index,:new,:create,:show,:edit] do
    collection do
      get 'get_children'
      get 'get_grand_children'
    end
  end
  resources :categories ,only: :new

  resources :card,only: [:new,:create,:destroy]

  resources :items,except: :index do
    resources :payments,only: [:new,:create]
  end

  get '/users/out', to: 'users#out'
  resources :users, only: [:show]

end

app/views/common/_left_side_menu.html.haml
.contents__left
  .contents__left__one
    %ul
      %li マイページ
      %li お知らせ
      %li やることリスト
      %li いいね！一覧
      %li 出品する
      %li 下書き一覧
      %li 出品した商品ー出品中
      %li 出品した商品ー取引中
      %li 出品した商品ー売却済み
      %li 購入した商品ー取引中
      %li ニュース一覧
      %li ガイド
      %li お問い合わせ
  .contents__left__two
    %h3 フリペイ
    %ul
      %li 売り上げ・振り込み申請
      %li ポイント
  .contents__left__three
    %h3 設定
    %ul
      %li プロフィール
      %li 発送元・お届け先住所変更
      - if current_user&.card
        %li= link_to "カード情報", new_card_path
      - else
        %li= link_to "カード情報登録", new_card_path
      %li メール/パスワード
      %li 本人情報
      %li 電話番号の確認
      %li= link_to "ログアウト", destroy_user_session_path,method: :delete

app/views/common/_main_header.html.haml
%header.header__all
  .header__all__main
    .mainHeader
      %h1.icon
        =link_to "/" do
          = image_tag "FURIMA_logo.svg"
      .searchmain
        %form{"accept-charset": "UTF-8", action: "#", method: "get"}
          %input{name: "utf8", type: "hidden", value: "✓"}
          %input#searchInput.searchmain--input{name: "key", placeholder: "キーワードから探す"}
          %button{type: "submit"}
            .searchmain__icon
              = image_tag "icon_search.png"
          %input{name: "authenticity_token", type: "hidden", value: "rGvQaEoXiWof9CviOMrABrWg8GvnR7RZ5CihIgqhun1x4Av6XJI7jRd8fffRfP5WFLbFT4wp6lPDQB+RLe9aTA=="}
      %ul.result-Lists
    .nav
      %ul.listsLeft
        %li.listsLeft__item.listsLeft__item--first
          .category
            = link_to "#", class: "category__search search__btn" do
              カテゴリー
            %ul.category__parent.category__list
              - @parents.each do |parent|
                %li
                  = link_to "#", class: "category__parent--name" do
                    = parent.name
                  %ul.category__child.category__list
                    - parent.children.each do |child|
                      %li.category_list2
                        = link_to "#", class: "category__child--name" do
                          = child.name
                        %ul.category__grandchild.category__list
                          - child.children.each do |grandchild|
                            %li.category_list3
                              = link_to "#", class: " category__child--name" do
                                = grandchild.name

        %li.listsLeft__item.listsLeft__item__second
          = link_to "#", id: "#brandBtn" do
            ブランド
          %ul.brandsPulldown.display-None
      %ul.lists-Right
        - if user_signed_in?
          %li.lists-Right__item
            = link_to "マイページ", user_path(current_user.id)
        - else
          %li.lists-Right__item
            = link_to "新規会員登録",new_user_registration_path
          %li.lists-Right__item
            = link_to "ログイン",new_user_session_path